#!/usr/bin/env zsh

hour="$(date +%H)"

declare -a apps=(
)

if [[ ! $(date +%u) -gt 5 ]]; then
    if [ "$hour" -ge "8" ] && [ "$hour" -lt "18" ]; then
        for app in "${apps[@]}"; do
            $app & disown
        done
    fi
fi
