# (Github Light) Colors for Wezterm

[colors]
background = '#ffffff'
foreground = '#1F2328'

cursor_bg = '#1F2328'
cursor_border = '#1F2328'
cursor_fg = '#ffffff'

selection_bg = '#bbdfff'
selection_fg = '#1F2328'

quick_select_label_bg = { Color = '#bbdfff' }
quick_select_label_fg = { Color = 'red' }
quick_select_match_bg = { Color = '#bbdfff' }
quick_select_match_fg = { Color = '#1F2328' }

ansi = [
    '#24292f',
    '#cf222e',
    '#116329',
    '#4d2d00',
    '#0969da',
    '#8250df',
    '#1b7c83',
    '#6e7781',
]
brights = [
    '#57606a',
    '#a40e26',
    '#1a7f37',
    '#633c01',
    '#218bff',
    '#a475f9',
    '#3192aa',
    '#8c959f',
]
