#!/usr/bin/env python3

import re
import sys

from pathlib import Path

address_to_add = sys.stdin.read().strip()
script_path = Path(sys.argv[1])

new_script = ""

KEEP_USER_DOMAINS = (
    "@gmail.com",
    "@hotmail.com",
    "@outlook.com",
)

SKIP_DOMAINS = (
    "@lists.openembedded.org",
    "@lists.yoctoproject.org",
    "@bootlin.com",
)

if m := re.match(r".+(@.+)", address_to_add):
    if m.group(1) in SKIP_DOMAINS:
        exit()

    if m.group(1) not in KEEP_USER_DOMAINS:
        address_to_add = m.group(1)

with open(script_path, "r") as script:
    addresses = []
    in_list = False
    for line in script.readlines():

        if "### SPAM_LIST_START ###" in line:
            in_list = True
            new_script += line
            continue

        if "### SPAM_LIST_END ###" in line:
            addresses.append(address_to_add)
            addresses = list(dict.fromkeys(addresses))
            address_list = [f'  header :contains "from" "{address}",' for address in list(addresses)]
            new_script += "\n".join(address_list)
            new_script = new_script[:-1]  # remove last comma
            new_script += "\n"
            new_script += line
            in_list = False
            continue

        if in_list:
            m = re.search('".+" "(.+)"', line)
            if m:
                addresses.append(m.group(1))
        else:
            new_script += line

with open(script_path, "w") as script:
    script.write(new_script)
